### ISSUE TITLE
执行bun run db:createAdmin时发生错误

### ISSUE THREAD

**Issue by MistyCN** [SMS-COSMO/the1068fm#3]
ubuntu 20.04

```
`$ tsx ./scripts/createDefaultUser.ts
Created default admin user. 
UserID: 'admin' 
Password: 'x5zWKoNSKs'
file:///www/wwwroot/b.szsygm.top/node_modules/@libsql/client/lib-esm/sqlite3.js:312
        return new LibsqlError(e.message, e.code, e.rawCode, e);
               ^

LibsqlError: SQLITE_ERROR: no such table: users
    at mapSqliteError (file:///www/wwwroot/b.szsygm.top/node_modules/@libsql/client/lib-esm/sqlite3.js:312:16)
    at executeStmt (file:///www/wwwroot/b.szsygm.top/node_modules/@libsql/client/lib-esm/sqlite3.js:222:15)
    at Sqlite3Client.execute (file:///www/wwwroot/b.szsygm.top/node_modules/@libsql/client/lib-esm/sqlite3.js:61:16)
    ... 4 lines matching cause stack trace ...
    at SQLiteSelectBase.then (/www/wwwroot/b.szsygm.top/node_modules/src/query-promise.ts:31:15) {
  code: 'SQLITE_ERROR',
  rawCode: 1,
  [cause]: SqliteError: no such table: users
      at convertError (/www/wwwroot/b.szsygm.top/node_modules/libsql/index.js:48:12)
      at Database.prepare (/www/wwwroot/b.szsygm.top/node_modules/libsql/index.js:111:13)
      at executeStmt (file:///www/wwwroot/b.szsygm.top/node_modules/@libsql/client/lib-esm/sqlite3.js:193:28)
      at Sqlite3Client.execute (file:///www/wwwroot/b.szsygm.top/node_modules/@libsql/client/lib-esm/sqlite3.js:61:16)
      at LibSQLPreparedQuery.values (/www/wwwroot/b.szsygm.top/node_modules/src/libsql/session.ts:247:57)
      at LibSQLPreparedQuery.all (/www/wwwroot/b.szsygm.top/node_modules/src/libsql/session.ts:176:27)
      at SQLiteSelectBase.all (/www/wwwroot/b.szsygm.top/node_modules/src/sqlite-core/query-builders/select.ts:884:26)
      at SQLiteSelectBase.execute (/www/wwwroot/b.szsygm.top/node_modules/src/sqlite-core/query-builders/select.ts:896:15)
      at SQLiteSelectBase.then (/www/wwwroot/b.szsygm.top/node_modules/src/query-promise.ts:31:15) {
    code: 'SQLITE_ERROR',
    rawCode: 1
  }
}

Node.js v18.20.4
error: script "db:createAdmin" exited with code 1
`
```
感谢

**Comment by MistyCN** [comment]
我创建了sqlite数据库，但是不知道如何设置环境变量的DATABASE_AUTH_TOKEN

**Comment by ZTL-UwU** [comment]
你可能没有跑 `db:push`。

> 我创建了sqlite数据库，但是不知道如何设置环境变量的DATABASE_AUTH_TOKEN

如果是本地的话不需要设置 `DATABASE_AUTH_TOKEN`，填空字符串就行

**Comment by MistyCN** [comment]
好的，数据库问题解决了，感谢！
