### ISSUE TITLE
执行bun run db:push时报错

### ISSUE THREAD

**Issue by 9Bakabaka** [SMS-COSMO/the1068fm#8]
### 系统环境
```
[root@Openstack-master the1068fm-1.3.0-stable]# cat /etc/*-release
NAME="Rocky Linux"
VERSION="9.4 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
Rocky Linux release 9.4 (Blue Onyx)
Rocky Linux release 9.4 (Blue Onyx)
Rocky Linux release 9.4 (Blue Onyx)
[root@Openstack-master the1068fm-1.3.0-stable]#
```

### Nodejs版本
```
[root@Openstack-master the1068fm-1.3.0-stable]# node
Welcome to Node.js v16.20.2.
Type ".help" for more information.
```

### bun版本
```
[root@Openstack-master the1068fm-1.3.0-stable]# bun --version
1.1.34
[root@Openstack-master the1068fm-1.3.0-stable]#
```

## 问题复现
执行`bun run db:push`时提示`This command is deprecated, please use updated 'push' command (see https://orm.drizzle.team/kit-docs/upgrade-21#how-to-migrate-to-0210)`，通过给出的连接执行`bun drizzle-kit push`报错.

```
[root@Openstack-master the1068fm-1.3.0-stable]# bun drizzle-kit push
No config path provided, using default 'drizzle.config.ts'
Reading config file '/root/the1068fm-1.3.0-stable/drizzle.config.ts'
_ZodError: [
  {
    "expected": "'postgresql' | 'mysql' | 'sqlite' | 'turso'",
    "received": "undefined",
    "code": "invalid_type",
    "path": [
      "dialect"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_union",
            "unionErrors": [
              {
                "issues": [
                  {
                    "received": "turso",
                    "code": "invalid_literal",
                    "expected": "d1-http",
                    "path": [
                      "driver"
                    ],
                    "message": "Invalid literal value, expected \"d1-http\""
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "received": "turso",
                    "code": "invalid_literal",
                    "expected": "expo",
                    "path": [
                      "driver"
                    ],
                    "message": "Invalid literal value, expected \"expo\""
                  }
                ],
                "name": "ZodError"
              }
            ],
            "path": [
              "driver"
            ],
            "message": "Invalid input"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_union",
            "unionErrors": [
              {
                "issues": [
                  {
                    "received": "turso",
                    "code": "invalid_literal",
                    "expected": "aws-data-api",
                    "path": [
                      "driver"
                    ],
                    "message": "Invalid literal value, expected \"aws-data-api\""
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "received": "turso",
                    "code": "invalid_literal",
                    "expected": "pglite",
                    "path": [
                      "driver"
                    ],
                    "message": "Invalid literal value, expected \"pglite\""
                  }
                ],
                "name": "ZodError"
              }
            ],
            "path": [
              "driver"
            ],
            "message": "Invalid input"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [
      "driver"
    ],
    "message": "Invalid input"
  }
]
    at Object.get error [as error] (/root/the1068fm-1.3.0-stable/node_modules/drizzle-kit/bin.cjs:2225:28)
    at drizzleConfigFromFile (/root/the1068fm-1.3.0-stable/node_modules/drizzle-kit/bin.cjs:18172:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async preparePushConfig (/root/the1068fm-1.3.0-stable/node_modules/drizzle-kit/bin.cjs:17793:29)
    at async run (/root/the1068fm-1.3.0-stable/node_modules/drizzle-kit/bin.cjs:87030:51) {
  issues: [
    {
      expected: "'postgresql' | 'mysql' | 'sqlite' | 'turso'",
      received: 'undefined',
      code: 'invalid_type',
      path: [Array],
      message: 'Required'
    },
    {
      code: 'invalid_union',
      unionErrors: [Array],
      path: [Array],
      message: 'Invalid input'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      expected: "'postgresql' | 'mysql' | 'sqlite' | 'turso'",
      received: 'undefined',
      code: 'invalid_type',
      path: [Array],
      message: 'Required'
    },
    {
      code: 'invalid_union',
      unionErrors: [Array],
      path: [Array],
      message: 'Invalid input'
    }
  ]
}
 Error  Please specify 'dialect' param in config file
error: "drizzle-kit" exited with code 1
[root@Openstack-master the1068fm-1.3.0-stable]#
```

## .env文件

```
DATABASE_URL="file:/root/db.sqlite"
DATABASE_CONNECTION_TYPE="local"
DATABASE_AUTH_TOKEN=""
NODE_ENV="development"
SERVER_URL="http://localhost:3000"
```

**Comment by ZTL-UwU** [comment]
请使用老版的 drizzle-orm。 the1068fm v1 不会再维护了。

**Comment by 9Bakabaka** [comment]
换了旧版本的 drizzle-orm 依然报错，版本是0.28.1

**Comment by ZTL-UwU** [comment]
```diff
- DATABASE_URL="file:/root/db.sqlite"
+ DATABASE_URL="/root/db.sqlite"
```

**Comment by 9Bakabaka** [comment]
> ```diff
> - DATABASE_URL="file:/root/db.sqlite"
> + DATABASE_URL="/root/db.sqlite"
> ```

改完之后报错了
'''
[root@Openstack-master the1068fm-1.3.0-stable]# bun run db:createAdmin
$ tsx ./scripts/createDefaultUser.ts
[ERROR] Invalid environment variables: {
    "_errors": [],
    "DATABASE_URL": {
        "_errors": [
            "Invalid url"
        ]
    }
}
error: script "db:createAdmin" exited with code 1
'''

**Comment by 9Bakabaka** [comment]
> ```diff
> - DATABASE_URL="file:/root/db.sqlite"
> + DATABASE_URL="/root/db.sqlite"
> ```

改完之后报错了

```
[root@Openstack-master the1068fm-1.3.0-stable]# bun run db:createAdmin
$ tsx ./scripts/createDefaultUser.ts
[ERROR] Invalid environment variables: {
    "_errors": [],
    "DATABASE_URL": {
        "_errors": [
            "Invalid url"
        ]
    }
}
error: script "db:createAdmin" exited with code 1
```

**Comment by ZTL-UwU** [comment]
修好了，还是用 `DATABASE_URL="file:/root/db.sqlite`。注意要有访问路径的权限。
